//! Report generation and result structures.
//!
//! This module defines the structure of Krino evaluation reports and provides
//! methods for generating, serializing, and validating reports.

use chrono::Utc;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::HashMap;

/// Complete evaluation report generated by Krino.
///
/// Every Krino evaluation produces a structured report that includes:
/// - Version information for reproducibility
/// - Input hashing for verification
/// - Per-module results with evidence
/// - Performance metrics
///
/// # Invariant
///
/// Two reports with the same `input_hash` and `model_versions` MUST produce
/// identical `results`. This is enforced by determinism tests in CI.
///
/// # Examples
///
/// ```
/// use krino::pipeline::KrinoReport;
///
/// let report = KrinoReport::new("context", "question", "answer");
/// assert!(report.metadata.deterministic);
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KrinoReport {
    /// Krino version that generated this report
    pub version: String,

    /// SHA256 hashes of all model weights used (`model_id` -> hash)
    pub model_versions: HashMap<String, String>,

    /// ISO 8601 timestamp of evaluation
    pub timestamp: String,

    /// SHA256 hash of inputs (for reproducibility verification)
    pub input_hash: String,

    /// Evaluation results from each module
    pub results: Vec<ModuleResult>,

    /// Metadata about the evaluation
    pub metadata: ReportMetadata,
}

/// Result from a single evaluation module.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModuleResult {
    /// Module name (e.g., "hallucination", "groundedness")
    pub module: String,

    /// Aggregate score [0.0, 1.0]
    pub score: f64,

    /// Whether the evaluation passed the configured threshold
    pub passed: bool,

    /// Wall-clock time for this module (milliseconds)
    pub latency_ms: f64,

    /// Detailed results (spans, claims, etc.)
    pub details: Vec<ModuleDetail>,
}

/// Detailed result from a module (evidence, spans, claims, etc.).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ModuleDetail {
    /// Hallucination span (token-level)
    HallucinationSpan {
        /// Start character position
        start: usize,
        /// End character position
        end: usize,
        /// Flagged text
        text: String,
        /// Confidence score [0.0, 1.0]
        confidence: f64,
        /// Description of the evidence gap
        evidence_gap: String,
    },

    /// NLI classification result
    NliClassification {
        /// The claim being evaluated
        claim: String,
        /// Classification: ENTAILMENT, CONTRADICTION, NEUTRAL
        label: String,
        /// Confidence score [0.0, 1.0]
        confidence: f64,
    },

    /// Similarity score
    SimilarityScore {
        /// Reference text
        reference: String,
        /// Candidate text
        candidate: String,
        /// Cosine similarity [0.0, 1.0]
        score: f64,
    },

    /// Schema validation error
    SchemaValidation {
        /// JSON path to the error (e.g., "/user/age")
        path: String,
        /// Error message describing the violation
        error: String,
    },

    /// PII detection result
    PiiDetection {
        /// Entity type (email, phone, ssn, etc.)
        entity_type: String,
        /// Detected PII value (masked)
        masked_value: String,
        /// Start position
        start: usize,
        /// End position
        end: usize,
    },
}

/// Metadata about the evaluation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReportMetadata {
    /// Total evaluation latency (milliseconds)
    pub total_latency_ms: f64,

    /// Whether context was provided
    pub context_provided: bool,

    /// List of modules that were executed
    pub modules_run: Vec<String>,

    /// Whether all modules are deterministic
    pub deterministic: bool,
}

impl KrinoReport {
    /// Creates a new report with the given inputs.
    ///
    /// This computes the input hash for reproducibility verification.
    ///
    /// # Arguments
    ///
    /// * `context` - Grounding context
    /// * `question` - Question or prompt
    /// * `answer` - LLM-generated answer
    #[must_use]
    pub fn new(context: &str, question: &str, answer: &str) -> Self {
        let input_hash = Self::compute_input_hash(context, question, answer);
        let timestamp = Utc::now().to_rfc3339();

        Self {
            version: env!("CARGO_PKG_VERSION").to_string(),
            model_versions: HashMap::new(),
            timestamp,
            input_hash,
            results: Vec::new(),
            metadata: ReportMetadata {
                total_latency_ms: 0.0,
                context_provided: !context.is_empty(),
                modules_run: Vec::new(),
                deterministic: true,
            },
        }
    }

    /// Computes SHA256 hash of inputs for reproducibility tracking.
    ///
    /// The hash is computed over the concatenation of context, question, and answer.
    ///
    /// # Determinism
    ///
    /// This function is deterministic: same inputs always produce the same hash.
    #[must_use]
    pub fn compute_input_hash(context: &str, question: &str, answer: &str) -> String {
        let mut hasher = Sha256::new();
        hasher.update(context.as_bytes());
        hasher.update(b"|");
        hasher.update(question.as_bytes());
        hasher.update(b"|");
        hasher.update(answer.as_bytes());
        format!("{:x}", hasher.finalize())
    }

    /// Adds a module result to the report.
    pub fn add_result(&mut self, result: ModuleResult) {
        self.metadata.modules_run.push(result.module.clone());
        self.metadata.total_latency_ms += result.latency_ms;
        self.results.push(result);
    }

    /// Sets the model versions used in this evaluation.
    pub fn set_model_versions(&mut self, versions: HashMap<String, String>) {
        self.model_versions = versions;
    }

    /// Returns whether all evaluations passed their thresholds.
    #[must_use]
    pub fn all_passed(&self) -> bool {
        self.results.iter().all(|r| r.passed)
    }

    /// Serializes the report to JSON.
    ///
    /// # Errors
    ///
    /// Returns an error if serialization fails.
    pub fn to_json(&self) -> serde_json::Result<String> {
        serde_json::to_string_pretty(self)
    }

    /// Deserializes a report from JSON.
    ///
    /// # Errors
    ///
    /// Returns an error if the JSON is invalid or doesn't match the schema.
    pub fn from_json(json: &str) -> serde_json::Result<Self> {
        serde_json::from_str(json)
    }
}

impl ModuleResult {
    /// Creates a new module result.
    ///
    /// # Arguments
    ///
    /// * `module` - Module name
    /// * `score` - Aggregate score [0.0, 1.0]
    /// * `threshold` - Passing threshold
    /// * `latency_ms` - Execution time in milliseconds
    pub fn new(module: impl Into<String>, score: f64, threshold: f64, latency_ms: f64) -> Self {
        Self {
            module: module.into(),
            score,
            passed: score >= threshold,
            latency_ms,
            details: Vec::new(),
        }
    }

    /// Adds a detail to this result.
    pub fn add_detail(&mut self, detail: ModuleDetail) {
        self.details.push(detail);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_report_creation() {
        let report = KrinoReport::new("context", "question", "answer");
        assert_eq!(report.version, env!("CARGO_PKG_VERSION"));
        assert!(!report.input_hash.is_empty());
        assert!(report.metadata.deterministic);
    }

    #[test]
    fn test_input_hash_deterministic() {
        let hash1 = KrinoReport::compute_input_hash("ctx", "q", "a");
        let hash2 = KrinoReport::compute_input_hash("ctx", "q", "a");
        assert_eq!(hash1, hash2);
    }

    #[test]
    fn test_input_hash_different_inputs() {
        let hash1 = KrinoReport::compute_input_hash("ctx1", "q", "a");
        let hash2 = KrinoReport::compute_input_hash("ctx2", "q", "a");
        assert_ne!(hash1, hash2);
    }

    #[test]
    fn test_context_provided_detection() {
        let report1 = KrinoReport::new("context", "q", "a");
        assert!(report1.metadata.context_provided);

        let report2 = KrinoReport::new("", "q", "a");
        assert!(!report2.metadata.context_provided);
    }

    #[allow(clippy::float_cmp)] // Allow exact float comparisons in tests
    #[test]
    fn test_add_result() {
        let mut report = KrinoReport::new("ctx", "q", "a");
        let result = ModuleResult::new("test_module", 0.8, 0.7, 50.0);

        report.add_result(result);

        assert_eq!(report.results.len(), 1);
        assert_eq!(report.metadata.modules_run.len(), 1);
        assert_eq!(report.metadata.total_latency_ms, 50.0);
    }

    #[test]
    fn test_module_result_passing() {
        let result1 = ModuleResult::new("module1", 0.8, 0.7, 10.0);
        assert!(result1.passed);

        let result2 = ModuleResult::new("module2", 0.6, 0.7, 10.0);
        assert!(!result2.passed);
    }

    #[test]
    fn test_all_passed() {
        let mut report = KrinoReport::new("ctx", "q", "a");
        report.add_result(ModuleResult::new("m1", 0.8, 0.7, 10.0));
        report.add_result(ModuleResult::new("m2", 0.9, 0.7, 10.0));
        assert!(report.all_passed());

        report.add_result(ModuleResult::new("m3", 0.5, 0.7, 10.0));
        assert!(!report.all_passed());
    }

    #[test]
    fn test_json_serialization() {
        let report = KrinoReport::new("ctx", "q", "a");
        let json = report.to_json().unwrap();
        assert!(json.contains("\"version\""));
        assert!(json.contains("\"input_hash\""));
    }

    #[test]
    fn test_json_round_trip() {
        let original = KrinoReport::new("ctx", "q", "a");
        let json = original.to_json().unwrap();
        let deserialized = KrinoReport::from_json(&json).unwrap();

        assert_eq!(original.version, deserialized.version);
        assert_eq!(original.input_hash, deserialized.input_hash);
        assert_eq!(
            original.metadata.deterministic,
            deserialized.metadata.deterministic
        );
    }

    #[test]
    fn test_module_detail_variants() {
        let detail1 = ModuleDetail::HallucinationSpan {
            start: 0,
            end: 10,
            text: "test".to_string(),
            confidence: 0.9,
            evidence_gap: "No support in context".to_string(),
        };

        let detail2 = ModuleDetail::PiiDetection {
            entity_type: "email".to_string(),
            masked_value: "***@***.com".to_string(),
            start: 5,
            end: 20,
        };

        // Test serialization
        let json1 = serde_json::to_string(&detail1).unwrap();
        let json2 = serde_json::to_string(&detail2).unwrap();

        assert!(json1.contains("HallucinationSpan"));
        assert!(json2.contains("PiiDetection"));
    }
}
